######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 9 20:06:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += processImage.h videodevice.h
SOURCES += main.cpp processImage.cpp videodevice.cpp
